# -*- coding: utf-8 -*-
"""data classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wPBrTBoTz61-C-JHL1_R49JX_57TfVl7

LOGISTIC REGRESSION
"""

import pandas as pd

pima = pd.read_csv('diabetes.csv')
pima.head()

Col_names = ['pregnant', 'glucose', 'bp', 'skin', 'insulin', 'bmi', 'pedigree', 'age', 'label']

del pima

pima = pd.read_csv('diabetes.csv', header =0, names=Col_names)

pima.head()

feature_cols = ['pregnant', 'glucose', 'bp', 'insulin', 'bmi', 'pedigree', 'age']

x = pima[feature_cols] # Question bank (mock test will be spillted from this)
y= pima.label #answer key

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=16)

x_train.head()

x_test.head()

len(x_train)

len(x)

len(x_test)

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(random_state=16)

logreg.fit(x_train, y_train)

from sklearn import metrics

y_pred = logreg.predict(x_test)

cnf = metrics.confusion_matrix(y_test, y_pred)

cnf

[['True positive', 'False negative'],
 ['False negative', 'True negative']]

