# -*- coding: utf-8 -*-
"""lets code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yogvzJQ4_6wj_3BN_IvoFy1oNqvAKb79
"""

print("Hello World!")